
FEDAVG = "FedAvg"

#SPARSIFICATION METHODS
NO_SPARSIFICATION = "None"
GLUEFL = "GlueFL"
STC = "STC"
APF = "APF"

# QUANTIZATION METHODS
NO_QUANTIZATION = "None"
QSGD = "QSGD"
QSGD_BUCKET = "QSGD_bucket"
LFL = "LFL"


# QUANTIZATION TARGET
FULL_MODEL = "FULL"
DIFF_MODEL = "DIFF"
DIFF_ESTIMATE = "DIFF_ESTIMATE"

# GlueFL PRESAMPLING STRATEGY
SIMPLE = "SIMPLE"
UNIFORM = "UNIFORM"
SPEED_PROB = "SPEED_PROB"
