# Configuration file of FAR training experiment

# ========== Cluster configuration ========== 
# ip address of the parameter server (need 1 GPU process)
ps_ip: 127.0.0.1

# ip address of each worker:# of available gpus process on each gpu in this node
# Note that if we collocate ps and worker on same GPU, then we need to decrease this number of available processes on that GPU by 1
# E.g., master node has 4 available processes, then 1 for the ps, and worker should be set to: worker:3
worker_ips: 
    - 127.0.0.1:[4]
    
exp_path: $FEDSCALE_HOME/examples/prefetch

# Entry function of executor and aggregator under $exp_path
executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: ""
    ssh_private_key: ~/.ssh/id_rsa

# cmd to run before we can indeed run FAR (in order)
setup_commands:
    - export PYTHONPATH='$FEDSCALE_HOME:$PYTHONPATH'
    - source $SLURM_TMPDIR/env/bin/activate   

# ========== Additional job configuration ========== 
# Default parameters are specified in config_parser.py, wherein more description of the parameter can be found

job_conf: 
    - job_name: FedAvg_baseline                 # Generate logs under this folder: log_path/job_name/time_stamp
    - log_path: $FEDSCALE_HOME/benchmark # Path of log files
    - num_participants: 30                      # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - data_set: femnist                     # Dataset: openImg, google_speech, stackoverflow
    - data_dir: $SLURM_TMPDIR/femnist    # Path of the dataset
    - data_map_file: $SLURM_TMPDIR/femnist/client_data_mapping/train.csv              # Allocation of data to each client, turn to iid setting if not provided
    - device_conf_file: $FEDSCALE_HOME/benchmark/dataset/data/device_info/client_device_capacity_ul_dl     # Path of the client trace
    - device_avail_file: $FEDSCALE_HOME/benchmark/dataset/data/device_info/client_behave_trace
    - compensation_dir: $SLURM_TMPDIR/compensation  
    - model: shufflenet_v2_x2_0                            # Models: e.g., shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2
    - eval_interval: 10                     # How many rounds to run a testing on the testing set
    - rounds: 1000                          # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - filter_less: 21                       # Remove clients w/ less than 21 samples
    - num_loaders: 2
    - local_steps: 10
    - learning_rate: 0.01
    - batch_size: 20
    - test_bsz: 32
    - use_cuda: False
    # Sampling
    - sampling_strategy: UNIFORM # Options: UNIFORM, STICKY
    # Sparsification
    - fl_method: FedAvg # Options: FedAvg, STC, GlueFL
    - total_mask_ratio: 1.0 # No sparsification - 1.0
    - shared_mask_ratio: 1.0 # No sparsification - 1.0
    # Quantization
    - download_compressor_type: None # Options: None, QSGD, QSGD_bucket, LFL
    - upload_compressor_type: None # Options: None, QSGD, QSGD_bucket, LFL
    - quantization_target: DIFF # Options: DIFF, FULL, DIFF_ESTIMATE
    - quantization_level: 127
    # Compensation
    - use_compensation: False
    # System factors
    - augmentation_factor: 0.4
    - download_factor: 0.8
    - upload_factor: 1.2
    # Prefetch
    - enable_prefetch: False
    - max_prefetch_round: 1
    # Overcommit
    - overcommitment: 1.3
    - overcommit_weight: 0.88 # The % of overcommitted clients allocated to the change group
